// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nncnlakxrtaloujeivvn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5uY25sYWt4cnRhbG91amVpdnZuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzU1MDU3MDgsImV4cCI6MjA1MTA4MTcwOH0.xhWORpDYC_LdWKabBmJxgvW4OQruDH2FPHfwoYQvn-Y";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);